import type { CategoryData, Item } from "./types"
import {
  LayoutDashboard,
  Truck,
  Store,
  Users,
  ShoppingCart,
  DollarSign,
  Settings,
  AlertCircle,
} from "lucide-react"

export const sidebarItems = [
  { icon: LayoutDashboard, label: "Dashboard", active: false },
  { icon: Truck, label: "Deliveries", active: false },
  { icon: Store, label: "Merchants", active: false, badge: true },
  { icon: Users, label: "Riders", active: false, badge: true },
  { icon: ShoppingCart, label: "Items", active: true },
  { icon: DollarSign, label: "Pricing", active: false },
  { icon: Settings, label: "Administration", active: false },
  { icon: AlertCircle, label: "Issues", active: false },
]

export const initialCategoryData: Record<string, CategoryData> = {
  supermarket: {
    icon: "/images/shopping-basket.png",
    title: "Supermarket",
    categories: [
      "Dairy Products",
      "Drinks",
      "Frozen Foods",
      "Canned Goods",
      "Health Foods",
      "Household Supplies",
      "Personal Care Products",
      "Beverages",
      "Snacks",
      "Meat and Seafood",
      "Condiments",
      "Fresh Produce",
      "Pet Supplies",
    ],
  },
  it: {
    icon: "/images/monitor.png",
    title: "IT & Gadgets",
    categories: [
      "Smartphones",
      "Laptops",
      "Tablets",
      "Headphones",
      "Cameras",
      "Gaming",
      "Smart Home",
      "Accessories",
      "Storage",
      "Networking",
      "Wearables",
      "Audio Equipment",
    ],
  },
  fashion: {
    icon: "/images/fashion.png",
    title: "Fashion & Lifestyle",
    categories: [
      "Women's Clothing",
      "Men's Clothing",
      "Shoes",
      "Bags & Accessories",
      "Jewelry",
      "Beauty & Cosmetics",
      "Watches",
      "Sunglasses",
      "Activewear",
      "Underwear",
      "Home Decor",
      "Fragrances",
    ],
  },
}

export const initialItems: Item[] = [
  // Supermarket - Drinks
  {
    id: "1",
    name: "Water",
    category: "Drinks",
    mainCategory: "Supermarket",
    icon: "/images/items/item-1.png",
    price: 1.5,
    stock: 100,
    description: "Pure drinking water",
    status: "active",
  },
  {
    id: "2",
    name: "Orange Juice",
    category: "Drinks",
    mainCategory: "Supermarket",
    icon: "/images/items/item-2.png",
    price: 3.5,
    stock: 50,
    description: "Fresh orange juice",
    status: "active",
  },
  {
    id: "3",
    name: "Coca Cola",
    category: "Drinks",
    mainCategory: "Supermarket",
    icon: "/images/items/item-3.png",
    price: 2.5,
    stock: 75,
    description: "Classic cola drink",
    status: "active",
  },
  // Supermarket - Dairy Products
  {
    id: "4",
    name: "Whole Milk",
    category: "Dairy Products",
    mainCategory: "Supermarket",
    icon: "/images/items/item-4.png",
    price: 3.0,
    stock: 60,
    description: "Fresh whole milk",
    status: "active",
  },
  {
    id: "5",
    name: "Greek Yogurt",
    category: "Dairy Products",
    mainCategory: "Supermarket",
    icon: "/images/items/item-5.png",
    price: 4.5,
    stock: 40,
    description: "Creamy Greek yogurt",
    status: "active",
  },
  // IT & Gadgets - Smartphones
  {
    id: "6",
    name: "iPhone 15 Pro",
    category: "Smartphones",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-6.png",
    price: 999.0,
    stock: 25,
    description: "Latest iPhone with advanced features",
    status: "active",
  },
  {
    id: "7",
    name: "Samsung Galaxy S24",
    category: "Smartphones",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-7.png",
    price: 899.0,
    stock: 30,
    description: "Premium Android smartphone",
    status: "active",
  },
  {
    id: "8",
    name: "Google Pixel 8",
    category: "Smartphones",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-8.png",
    price: 699.0,
    stock: 20,
    description: "Google's flagship phone with AI features",
    status: "active",
  },
  // IT & Gadgets - Laptops
  {
    id: "9",
    name: 'MacBook Pro 16"',
    category: "Laptops",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-9.png",
    price: 2499.0,
    stock: 15,
    description: "Professional laptop for creators",
    status: "active",
  },
  {
    id: "10",
    name: "Dell XPS 13",
    category: "Laptops",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-1.png",
    price: 1299.0,
    stock: 18,
    description: "Ultrabook with premium design",
    status: "active",
  },
  {
    id: "11",
    name: "ThinkPad X1 Carbon",
    category: "Laptops",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-2.png",
    price: 1599.0,
    stock: 12,
    description: "Business laptop with durability",
    status: "active",
  },
  // IT & Gadgets - Headphones
  {
    id: "12",
    name: "AirPods Pro",
    category: "Headphones",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-3.png",
    price: 249.0,
    stock: 50,
    description: "Wireless earbuds with noise cancellation",
    status: "active",
  },
  {
    id: "13",
    name: "Sony WH-1000XM5",
    category: "Headphones",
    mainCategory: "IT & Gadgets",
    icon: "/images/items/item-4.png",
    price: 399.0,
    stock: 35,
    description: "Premium noise-canceling headphones",
    status: "active",
  },
  // Fashion & Lifestyle - Women's Clothing
  {
    id: "14",
    name: "Summer Dress",
    category: "Women's Clothing",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-1.png",
    price: 89.0,
    stock: 45,
    description: "Elegant summer dress for casual wear",
    status: "active",
  },
  {
    id: "15",
    name: "Silk Blouse",
    category: "Women's Clothing",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-2.png",
    price: 129.0,
    stock: 30,
    description: "Premium silk blouse for office wear",
    status: "active",
  },
  {
    id: "16",
    name: "Denim Jacket",
    category: "Women's Clothing",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-3.png",
    price: 79.0,
    stock: 25,
    description: "Classic denim jacket",
    status: "active",
  },
  // Fashion & Lifestyle - Men's Clothing
  {
    id: "17",
    name: "Cotton T-Shirt",
    category: "Men's Clothing",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-4.png",
    price: 29.0,
    stock: 80,
    description: "Comfortable cotton t-shirt",
    status: "active",
  },
  {
    id: "18",
    name: "Formal Shirt",
    category: "Men's Clothing",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-5.png",
    price: 69.0,
    stock: 40,
    description: "Professional formal shirt",
    status: "active",
  },
  {
    id: "19",
    name: "Chino Pants",
    category: "Men's Clothing",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-6.png",
    price: 59.0,
    stock: 35,
    description: "Casual chino pants",
    status: "active",
  },
  // Fashion & Lifestyle - Shoes
  {
    id: "20",
    name: "Running Shoes",
    category: "Shoes",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-7.png",
    price: 129.0,
    stock: 60,
    description: "Comfortable running shoes",
    status: "active",
  },
  {
    id: "21",
    name: "Leather Boots",
    category: "Shoes",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-8.png",
    price: 199.0,
    stock: 25,
    description: "Premium leather boots",
    status: "active",
  },
  {
    id: "22",
    name: "High Heels",
    category: "Shoes",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-9.png",
    price: 149.0,
    stock: 30,
    description: "Elegant high heel shoes",
    status: "active",
  },
  // Fashion & Lifestyle - Beauty & Cosmetics
  {
    id: "23",
    name: "Foundation",
    category: "Beauty & Cosmetics",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-1.png",
    price: 45.0,
    stock: 50,
    description: "Long-lasting foundation",
    status: "active",
  },
  {
    id: "24",
    name: "Lipstick",
    category: "Beauty & Cosmetics",
    mainCategory: "Fashion & Lifestyle",
    icon: "/images/items/item-2.png",
    price: 25.0,
    stock: 75,
    description: "Matte finish lipstick",
    status: "active",
  },
]
